# Generated by Django 4.2.1 on 2024-01-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=255)),
                ('price', models.TextField(max_length=255)),
                ('orderno', models.IntegerField(blank=True, null=True)),
                ('qunatity', models.IntegerField(blank=True, null=True)),
                ('category', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=220, null=True)),
            ],
        ),
    ]
